name: Always Fail Action

on:
  pull_request:

jobs:
  fail_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Always Fail Step
      run: exit 0
